Сетки index.html без футера
htmlacademy-adaptive/1307951-cat-energy-20 pull request #5
Opened 2020-08-25 12:36 UTC by gerrymander-web

Тревис ругался, но это недоставленные пробелы. Я их попозже поправлю

2020-08-26 00:09 UTC, gerrymander-web commented
Я немного "перестаралась" и сделала больше чем просто адаптивные сетки. Добавила еще некоторые стили к элементам, которые должны быть в следующем задании. Увлеклась в какой-то момент, а потом решила оставить. Жалко стало все удалять.  В общем, я почти со всем разобралась, правда путаюсь с сущностями и их описанием. Могла лишнего не в тот класс поставить.

2020-08-26 00:16 UTC, gerrymander-web commented
У меня еще вопрос есть. Я посмотрела несколько раз видео с обзором проекта. В общем, я не поняла что делать с картой в футере. По идее ей надо поставить предел, но я сомневаюсь какой (1400px?) И еще хочется также поставить границу на минимальный размер (Это надо делать вообще... по-жизни так сказать?). 

И еще один момент. Я там добавляла псевдоэлементы и псевдоклассы внутри элемента, а потом внутри них писала правила для планшета и десктопа. Так можно делать? или надо отдельно выносить??? Вложенность-то получается больше 2-х уже. 

В общем, я по-тихому буду остальные страницы делать, но не шибко быстро. До субботы точно. С начала выходных должно появиться больше времени. Вроде все идут на поправку.

2020-08-26 00:41 UTC, gerrymander-web commented
И еще вопрос есть. Я там почти везде наставила пиксели, что, наверное, не очень хорошо. Как понять, когда надо ставить относительные единицы и к каким свойствам (внешние/внутренние отступы и/или размеры боксов )?  Я запуталась в этой логике, которую не поняла,  и не стала рисковать.

2020-08-26 00:44 UTC, gerrymander-web commented
Кота я все-таки добавила в шапку, потому что в десктопной версии он, вроде, к навигации относится.

2020-08-26 18:32 UTC, gerrymander-web commented
Вот еще один вопрос появился. Я в индексе изначально хотела сделать общий контейнер и обозначить там выравнивание по центру и внутренние отступы. Потом решила делать такое центрирование для отдельных блоков из-зы фонов, которые выходят за пределы внутренних границ. А сейчас сижу и думаю, что зря я это, наверное, сделала. В общем, вопрос в том, как вообще такие фоны делаются? Я имею в виду общую практику фронтэнда. У меня пока три варианта: делать блоки отдельно, сделать дополнительный wrapper (хотя, это гипотетический вариант), с помощью before\after. Есть еще варианты?

2020-08-31 11:03 UTC, AleksandrLv commented
> У меня еще вопрос есть. Я посмотрела несколько раз видео с обзором проекта. В общем, я не поняла что делать с картой в футере. По идее ей надо поставить предел, но я сомневаюсь какой (1400px?) И еще хочется также поставить границу на минимальный размер (Это надо делать вообще... по-жизни так сказать?).
> 
> И еще один момент. Я там добавляла псевдоэлементы и псевдоклассы внутри элемента, а потом внутри них писала правила для планшета и десктопа. Так можно делать? или надо отдельно выносить??? Вложенность-то получается больше 2-х уже.
> 
> В общем, я по-тихому буду остальные страницы делать, но не шибко быстро. До субботы точно. С начала выходных должно появиться больше времени. Вроде все идут на поправку.

У карты нет предела. Всегда на всю ширину
Минимальную ширину 320px обычно всегда ставят
С псевдоэлементами и псевдоклассами можно

2020-08-31 11:05 UTC, AleksandrLv commented
> И еще вопрос есть. Я там почти везде наставила пиксели, что, наверное, не очень хорошо. Как понять, когда надо ставить относительные единицы и к каким свойствам (внешние/внутренние отступы и/или размеры боксов )? Я запуталась в этой логике, которую не поняла, и не стала рисковать.

Там вроде всё логично. Если надо, чтобы блок всегда оставался одного размера, то пиксели, иначе относительные единицы. Можем разобрать конкретный пример, который тебе не понятен в телеграме

2020-08-31 12:05 UTC, AleksandrLv commented
> гипотетический

Я обычно делал два и более блоков. Универсальный блок может больше проблем создать, чем несколько конкретных блоков

2020-09-01 06:01 UTC, AleksandrLv commented on source/sass/blocks/page-header.scss
> +    padding-bottom: 0;
Обычно, используют сокращения padding: 24px 30px 0 30px

2020-09-01 06:02 UTC, AleksandrLv commented on source/index.html
>            <li class="site-list__item site-list__item--active">Главная</li>
Это ссылки должны быть на разные разделы

2020-09-01 06:03 UTC, AleksandrLv commented on source/index.html
> +        <ol class="mechanism__list">
Почему ol? Тут же нет нумерации

2020-09-01 12:52 UTC, gerrymander-web commented on source/index.html
> +        <ol class="mechanism__list">
нумерации нет только на мобильной версии, а дальше она есть

2020-09-01 12:52 UTC, gerrymander-web commented on source/index.html
>            <li class="site-list__item site-list__item--active">Главная</li>
забыла поставить ссылки.

2020-09-01 12:54 UTC, gerrymander-web commented on source/sass/blocks/page-header.scss
> +    padding-bottom: 0;
ну, мне сокращенные версии не очень нравится писать, я путаю с какого они начинаются (top и  left). Со временем привыкну. Это с одной стороны. А с другой, там Вадим в лекциях сначала постоянно говорил, что сокращенные варианты  это не комильфо.

2020-09-01 12:55 UTC, gerrymander-web commented on source/sass/blocks/page-header.scss
> +  box-sizing: border-box;
Я про этот критерий забыла. Я вообще забыла поставить глобальные стили. блииин. Ладно, исправлю.

2020-09-01 22:31 UTC, gerrymander-web commented
Проверь, пожалуйста, сначала реализацию зеленой декоративной линии у заголовка sideline блока. Может есть альтернативный вариант? менее трудоемкий?

2020-09-03 19:55 UTC, gerrymander-web commented
Сделала небольшую коррекцию индекса (Поменяла почти все, кроме блока со сравнением кота. Его подработаю, если время останется, потому что его можно почти не делать по заданию). Картинки вставила, но так... правильно вставлю попозже. Также изменила зелёную линию в каталоге. Вроде все нормально. Скрола нет.

2020-09-05 18:07 UTC, AleksandrLv requested changes

2020-09-05 20:37 UTC, merged